/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303034",
        "surface-variant": "#353439",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#f8d8ff",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-fixed": "#002022",
        "on-surface-variant": "#b9cacb",
        "surface-container": "#1f1f23",
        "surface-container-lowest": "#0e0e12",
        "surface-tint": "#00dbe9",
        "surface-container-low": "#1b1b1f",
        "surface-container-high": "#2a2a2e",
        "on-primary-container": "#006970",
        "primary-fixed-dim": "#00dbe9",
        "on-secondary": "#520072",
        "inverse-primary": "#006970",
        "on-secondary-container": "#fff6fc",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface-bright": "#39393d",
        "secondary": "#ebb2ff",
        "outline": "#849495",
        "tertiary-fixed-dim": "#c9c6c5",
        "inverse-surface": "#e4e1e7",
        "tertiary": "#f9f5f5",
        "tertiary-container": "#dcd9d8",
        "surface-container-highest": "#353439",
        "secondary-fixed-dim": "#ebb2ff",
        "primary-container": "#00f0ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#74009f",
        "on-secondary-fixed": "#320047",
        "primary": "#dbfcff",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-dim": "#131317",
        "on-tertiary": "#313030",
        "primary-fixed": "#7df4ff",
        "on-error": "#690005",
        "on-primary": "#00363a",
        "on-background": "#e4e1e7",
        "secondary-container": "#b600f8",
        "on-tertiary-container": "#605e5e",
        "background": "#131317",
        "surface": "#131317",
        "outline-variant": "#3b494b",
        "on-surface": "#e4e1e7",
        "on-tertiary-fixed-variant": "#474646"
      },
      fontFamily: {
        "body-base": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "display-lg": ["Inter"],
        "status-sm": ["Geist"],
        "headline-lg": ["Inter"]
      },
      spacing: {
        "base-unit": "4px",
        "grid-columns": "12",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      }
    },
  },
  plugins: [],
}
